spring:
  application:
    name: multipleDatasource
  datasource:
    url: jdbc:mysql://192.168.99.151:3306/store?serverTimezone=UTC&characterEncoding=utf-8
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: false
          format_sql: true
          use_sql_comments: true
  data:
    mongodb:
      database: fbd_shop
      host: 192.168.99.42
      port: 27018
fbd-shop-app:
  url: http://uatscbackend.fujfu.com